# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot.initrd.availableKernelModules = [
    "uhci_hcd"
    "ehci_pci"
    "ahci"
    "virtio_pci"
    "virtio_scsi"
    "sd_mod"
    "sr_mod"
  ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelParams = [
    "console=tty0"
    "console=ttyS0,115200n8"
    "mitigations=off"
    "amd_iommu=on"
    "split_lock_detect=off"
  ];
  boot.initrd.kernelModules = [
    "vfio_pci"
    "vfio"
    "vfio_iommu_type1"
    "amdgpu" # Load after VFIO modules
  ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/858c0bd1-7c4d-47c8-ac8e-ce020a021537";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7440-56ED";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.enableAllFirmware = true;
  hardware.firmware = with pkgs; [ linux-firmware ];

  # Hardware acceleration with RDNA 4 support
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      mesa
      amdvlk # Alternative Vulkan driver
      rocmPackages.clr.icd # OpenCL support
    ];
    extraPackages32 = with pkgs; [ driversi686Linux.amdvlk ];
  };

  # Video drivers for display server
  services.xserver.videoDrivers = [ "amdgpu" ];

  # Environment variables for optimal performance
  environment.variables = {
    AMD_VULKAN_ICD = "RADV"; # Use Mesa RADV by default
    ROC_ENABLE_PRE_VEGA = "1"; # Compatibility setting
  };

}
